### ISSUE TITLE
Coloured DotDigraph output

### ISSUE THREAD

**Issue by flsmith** [digraphs/Digraphs#170]
Related to #169, it would be nice to be able to specify vertex/edge colours in `DotDigraph`, e.g. be able to do

`DotDigraph(dg, vertcolors, edgecolors)`

where 'vertcolors' and 'edgecolors' are specified in some manner (maybe by lists with holes, maybe by lists of tuples etc.)

(also I'll probably do this myself soon)

**Comment by james-d-mitchell** [comment]
This was resolved in PR #330.

**Comment by james-d-mitchell** [comment]
Resolved in v1.4.0
