### ISSUE TITLE
Document all of the configuration options in the README and manual

### ISSUE THREAD

**Issue by egri-nagy** [digraphs/Digraphs#320]
-mpopcnt gcc flag is not available on ARM, so compilation fails.

Quick fix: Manually removing  the flag from the Makefile.

**Comment by james-d-mitchell** [comment]
@egri-nagy better than the quick fix is the quicker and proper fix: use the flag ‘—without-intrinsics’ when running ‘./configure’. Admittedly this is probably not documented anywhere but it should be.

**Comment by james-d-mitchell** [comment]
I suggest that this issue remain open until all of the configuration options have been documented in the README and in the manual.

**Comment by wilfwilson** [comment]
Resolved in v1.4.1.
