### ISSUE TITLE
Migrate from Travis to Github Actions

### ISSUE THREAD

**Issue by flsmith** [digraphs/Digraphs#339]
Because of the changes detailed [here](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), Travis is probably unsuitable for use as our CI now. Max Horn suggested using Github actions (as can be seen in this [WIP PR](https://github.com/gap-system/gap/pull/4036)), and I think it's the right call. For public repositories, it doesn't have a usage cap, and it seems to have all the relevant features that Travis did.

**Comment by james-d-mitchell** [comment]
See #348 and #342.

**Comment by james-d-mitchell** [comment]
I think we can consider this issue closed now, no?

**Comment by wilfwilson** [comment]
Agreed.
