### ISSUE TITLE
Implement VerticesReachableFrom

### ISSUE THREAD

**Issue by james-d-mitchell** [digraphs/Digraphs#353]
At present there isn't a convenient way of obtaining a list of all of the vertices reachable from a given vertex in a digraph. The purpose of this issue is to add such a method, perhaps called `VerticesReachableFrom`, but maybe there's a more snappy name too. 

Just to note that, I sort of expected that `DigraphConnectedComponent` might have the desired functionality, but `DigraphConnectedComponent` returns everything reachable from a given vertex and everything that can reach that vertex (so a superset of the desired output for `VerticesReachableFrom`). 

I imagine the implementation of this would be a straightforward DFS started at the specified root node.

**Comment by marinaanagno** [comment]
@james-d-mitchell  I had a look on that just now and `DigraphPath` returns a non-trivial directed path between two vertices, if one exists, so this bit of code seems to give the correct result. I tested it on the graphs I was using for dominators and it gives the same result. It does not run a DFS tough, possibly `DigraphPath` does already. Should I submit the pull request or isn't this what we are looking for?
`IsReachableFrom := function(D, u)
  local v, C;
  C := [u];
  for v in DigraphVertices(D) do
    if not DigraphPath(D, u, v) = fail then
      Add(C, v);
    fi;
  od;
  return C;   
end;`

**Comment by james-d-mitchell** [comment]
Resolved by #379

**Comment by james-d-mitchell** [comment]
Resolved in. 1.4.0
