### ISSUE TITLE
Updating GAP package update system

### ISSUE THREAD

**Issue by alex-konovalov** [digraphs/Digraphs#381]
Check for package updates fails:
```
  WARNING (Digraphs): no success in download of the current info file 
  from https://gap-packages.github.io/Digraphs/PackageInfo.g
```
Is it now the time to update https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/currentPackageInfoURLList ?

**Comment by james-d-mitchell** [comment]
I think this is resolved, is that right @alex-konovalov ?

**Comment by alex-konovalov** [comment]
Thanks - yes, @james-d-mitchell !
