### ISSUE TITLE
Check consistency of named digraphs before release?

### ISSUE THREAD

**Issue by wilfwilson** [digraphs/Digraphs#444]
We have e.g. `KingsGraph` but `StarDigraph` (Graph versus digraph).

We might want to rethink and tweak some names to make things more consistently.
We might want to do this **after everything is merged**, just to make this change as quick as possible (and without bothering lots of people).

Here is a list of the things that are currently in `master` branch. This should hopefully let us solidify on a policy, and see what needs to be changed (if anything).

### Symmetric digraphs with name `BlahGraph`

* `PetersenGraph`
* `GeneralisedPetersenGraph`
* `LollipopGraph`
* `SquareGridGraph`
* `TriangularGridGraph`
* `HaarGraph`
* `KingsGraph`
* `KnightsGraph`
* `BananaTree`

### Symmetric digraphs with name `BlahDigraph` (perhaps should be called `BlahGraph`?)

Standard examples:
* `StarDigraph`
* `TadpoleDigraph`
* `BookDigraph`
* `JohnsonDigraph`

Standard constructions (I think these are fine as digraph):
* `CompleteDigraph`
* `CompleteBipartiteDigraph`
* `CompleteMultipartiteDigraph`
* `EmptyDigraph`
* `NullDigraph`

### Not-symmetric digraphs with name `BlahGraph` (bad!)

* None that I've found so far (good!)

### Not-symmetric digraphs with name `BlahDigraph` (good)

* `ChainDigraph`
* `CycleDigraph`

**Comment by LRacine** [comment]
@wilfwilson Should they all end with Digraph?

**Comment by wilfwilson** [comment]
I'm not sure. The 'might want to' was meant honestly – we also might not want to 🙂. I'd be happy for people to weigh in with their opinions. I just happened to notice the apparent inconsistency and thought I'd create an issue.

It could be that some examples are named one particular way in common usage, and we should probably stick with that where possible. e.g. the Digraphs package already has the `PetersenGraph` function which creates the somewhat-famous Petersen graph. For examples where this is not the case, though, I would _probably_ advocate for using the suffix `Digraph`.

Or perhaps having synonyms in each case would be best? So that e.g. both `StarDigraph` and `StarGraph` work.

**Comment by wilfwilson** [comment]
I have updated the original issue with information about what currently is in the `master` branch of the package. So far, I would at least propose renaming `StarDigraph`, `TadpoleDigraph`, and `BookDigraph` to `StarGraph`, `TadpoleGraph`, and `BookGraph`.

@LRacine 

(We can't rename `JohnsonDigraph` to `JohnsonGraph` because `JohnsonGraph` is already claimed by the Grape package).
