### ISSUE TITLE
List of depth-first searches that can be replaced with the generic one

### ISSUE THREAD

**Issue by james-d-mitchell** [digraphs/Digraphs#455]

**Comment by LRacine** [comment]
As of now we have:
- DIGRAPHS_ArticulationPointsBridgesStrongOrientation
- DominatorTree
- VerticesReachableFrom
- IteratorOfPaths
- DIGRAPHS_BipartiteMatching
- DIGRAPHS_GeneralMatching

**Comment by wilfwilson** [comment]
I'm not sure whether you're going to make a generic C implementation too, but anyway, I think these are all pretty basic depth-first searches in `src/digraphs.c`:
* `FuncDIGRAPH_PATH`
* `FuncDIGRAPH_SYMMETRIC_SPANNING_FOREST`
* `FuncDIGRAPH_TOPO_SORT`
* `FuncDIGRAPH_LONGEST_DIST_VERTEX`
* `FuncIS_ACYCLIC_DIGRAPH`
* `FuncIS_ANTISYMMETRIC_DIGRAPH`
