### ISSUE TITLE
AppVeyor tests fail

### ISSUE THREAD

**Issue by wilfwilson** [digraphs/Digraphs#463]
The AppVeyor tests started to fail a few weeks ago, even though nothing had changed with Digraphs, as you can see on the AppVeyor website: https://ci.appveyor.com/project/james-d-mitchell/digraphs-0gul0/history

Here is an example of what goes wrong.
```
Compiling the Digraphs package...
Can't locate threads.pm in @INC (you may need to install the threads module) (@INC contains: /usr/share/automake-1.16 /usr/local/lib/perl5/site_perl/5.32/x86_64-cygwin-threads /usr/local/share/perl5/site_perl/5.32 /usr/lib/perl5/vendor_perl/5.32/x86_64-cygwin-threads /usr/share/perl5/vendor_perl/5.32 /usr/lib/perl5/5.32/x86_64-cygwin-threads /usr/share/perl5/5.32) at /usr/share/automake-1.16/Automake/ChannelDefs.pm line 23.
BEGIN failed--compilation aborted at /usr/share/automake-1.16/Automake/ChannelDefs.pm line 26.
Compilation failed in require at /usr/share/automake-1.16/Automake/Configure_ac.pm line 27.
BEGIN failed--compilation aborted at /usr/share/automake-1.16/Automake/Configure_ac.pm line 27.
Compilation failed in require at /usr/bin/aclocal-1.16 line 38.
BEGIN failed--compilation aborted at /usr/bin/aclocal-1.16 line 38.
autoreconf-2.69: aclocal failed with exit status: 2
```
Unless you magically know what is going on and how to fix it, I think this is probably the point at which we should stop using Appveyor, what do you think @james-d-mitchell?

**Comment by james-d-mitchell** [comment]
I think we should disable appveyor for the time being and possibly permanently. A similar issue arose in libsemigroups and I wasn’t able to figure out how to resolve it in the amount of time I was willing to spend on it.

**Comment by wilfwilson** [comment]
I have 'suspended' the AppVeyor integration in the digraphs organisation settings. I hoped that that would mean the AppVeyor check stops appearing on PRs, but it hasn't so far (see https://github.com/digraphs/Digraphs/pull/449 which I just rebased) but perhaps that takes time to propogate.

Otherwise, we should either remove/rename the `.appveyor.yml` file, or completely uninstall the AppVeyor integration.

**Comment by wilfwilson** [comment]
I had to remove a webhook from the repository (or perhaps it was from the Digraphs organisation). Anyway, AppVeyor is now gone from both the `stable-1.4` and `master` branches, so I'm going to close this.

We can also revert the commit that #466 added, and re-install the appropriate GitHub/AppVeyor integration, if we want to get it back.
