### ISSUE TITLE
Is Digraphs faster in 32-bit?!

### ISSUE THREAD

**Issue by wilfwilson** [digraphs/Digraphs#474]
Looking here: https://dev.azure.com/jdm3/jdm3/_build/results?buildId=1010&view=results (which does not seem to be atypical), the GAP 4.11 64-bit job takes nearly twice as long as the GAP 4.11 32-bit job. Perhaps I'm missing something, but they seem to me to be doing the same thing, so why is there such a big difference?

(Note that NautyTracesInterface doesn't support GAP 4.10, which explains why the 4.10 jobs are faster still).

**Comment by james-d-mitchell** [comment]
The 32 bit tests are faster! But the reason is this line:

**Comment by wilfwilson** [comment]
That's a relief!
