### ISSUE TITLE
Implement RandomDigraph(IsAcyclicDigraph, etc);

### ISSUE THREAD

**Issue by james-d-mitchell** [digraphs/Digraphs#497]
It'd be great if we could have an implementation of `RandomDigraph(IsAcyclicDigraph, *)` here's a basic attempt:

~~~~
RandomAcyclicDigraph := function(n)
  local mat, i, j;
  mat := [];
  for i in [1 .. n - 1] do
    mat[i] := ListWithIdenticalEntries(n, 0);
    for j in [i + 1 .. n] do
      mat[i][j] := Random([0 .. 2]);
    od;
  od;
  Add(mat, ListWithIdenticalEntries(n, 0));

  return DigraphByAdjacencyMatrix(mat);
end;
~~~~

which obviously has lots of issues.

**Comment by wilfwilson** [comment]
Yeah, that would be nice to have.

Your sample code is a decent starting point, my immediate suggestion would be to add an `OnDigraphs(*, Random(SymmetricGroup(n))` before returning.

**Comment by mtorpey** [comment]
It looks like Kamran, an SH student in BSc CS/Maths, will be working on this and related topics as part of a CS4098 project this year!

**Comment by james-d-mitchell** [comment]
Nice!

**Comment by james-d-mitchell** [comment]
Just to record the following would be handy `RandomDigraph(IsUndirectedSpanningTree,...`

**Comment by mtorpey** [comment]
Happy to say that Kamran is still working on this!

**Comment by mtorpey** [comment]
Done, as of #531.
