### ISSUE TITLE
`String` for a digraph can sometimes wrongly return `"CycleDigraph(n)"`

### ISSUE THREAD

**Issue by wilfwilson** [digraphs/Digraphs#517]
The problem is that `IsCycleDigraph` is a property concerning _isomorphism type_, whereas `CycleDigraph(n)` creates a _specific_ cycle digraph. So this is fine:
```
gap> D1 := CycleDigraph(6);;
gap> String(D1);
"CycleDigraph(6)"
gap> D1 = EvalString(String(D1));
true
```
But this should return a different string:
```
gap> D2 := DigraphReverse(D1);;
gap> IsCycleDigraph(D2);
true
gap> String(D2);
"CycleDigraph(6)"
gap> D2 = EvalString(String(D2));
false
```

**Comment by james-d-mitchell** [comment]
This will be resolved in v1.6.0 (or earlier).
