### ISSUE TITLE
Implement `IsOrderIdeal` for a subset of a partial order digraph

### ISSUE THREAD

**Issue by james-d-mitchell** [digraphs/Digraphs#522]
This property would return `true` if the specified subset was "downwards" closed, i.e. contains every node less than the given nodes. This could more or less easily be done using `VerticesReachableFrom` if `VerticesReachableFrom` could take a list of nodes.

**Comment by DanielPointon** [comment]
I'll be working on this following discussion in weekly meeting.

**Comment by james-d-mitchell** [comment]
We could also add `IsOrderFilter` by replacing `downwards` with `upwards` in the original comment.

**Comment by DanielPointon** [comment]
https://github.com/digraphs/Digraphs/pull/609

**Comment by james-d-mitchell** [comment]
@ zljlzljlz Do you think you could try to implement a method for `IsOrderFilter` which would be almost identical to the method that Daniel did for `IsOrderIdeal`?
