### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by james-d-mitchell** [digraphs/Digraphs#524]
I propose that we change the name of the default branch from `master` to `main`, but wanted to double check that no one objects before the change is made. Thoughts?

**Comment by james-d-mitchell** [comment]
@wilfwilson @mtorpey @flsmith in particular, any thoughts?

**Comment by mtorpey** [comment]
No objections from me.  `master` is *so* 2021.

**Comment by james-d-mitchell** [comment]
Exactly thanks @mtorpey !

**Comment by wilfwilson** [comment]
What's the reason for the proposal?

**Comment by james-d-mitchell** [comment]
The purpose is to avoid the negative connotations associated to the word `master` as described:

https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main

Doing this at the start of 2022 seemed like an opportune moment.

**Comment by flsmith** [comment]
Agreed

**Comment by james-d-mitchell** [comment]
So, let's make this change on the 1st of May, just so as to do it with some forewarning?

**Comment by james-d-mitchell** [comment]
I did this yesterday, which wasn't the 1st of May, but there you go...
