### ISSUE TITLE
kernel module built on OpenBSD is broken

### ISSUE THREAD

**Issue by dimpase** [digraphs/Digraphs#562]
On OpenBSD 7.1 with clang 13, `digraphs` pkg builds seemigly OK, but loading the kernel module fails:
```
 ./gap
 *********   GAP 4.13dev-154-g4afcec9 built on 2022-11-23 22:23:51+0100
 *  GAP  *   https://www.gap-system.org
 *********   Architecture: x86_64-unknown-openbsd7.1-default64-kv8
 Configuration:  gmp 6.2.1, GASMAN
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.6, AutPGrp 1.11, CRISP 1.4.5, Cryst 4.1.25, 
             CrystCat 1.1.10, CTblLib 1.3.4, FactInt 1.6.3, FGA 1.4.0, Forms 1.2.9, GAPDoc 1.6.6, 
             genss 1.6.8, IO 4.8.0, IRREDSOL 1.4.4, LAGUNA 3.9.5, orb 4.9.0, Polenta 1.3.10, 
             Polycyclic 2.16, PrimGrp 3.4.2, RadiRoot 2.9, recog 1.4.2, ResClasses 4.7.3, 
             SmallGrp 1.5.1, Sophus 1.27, SpinSym 1.5.2, TomLib 1.2.9, TransGrp 3.6.3, 
             utils 0.78
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> LoadPackage("digraphs");
------------------------------------------------------------------------------------------------
Loading  datastructures 0.3.0 (datastructures - GAP Data Structures)
by Markus Pfeiffer (http://www.morphism.de/~markusp),
   Max Horn (https://www.quendi.de/math),
   Christopher Jefferson (http://caj.host.cs.st-andrews.ac.uk/), and
   Steve Linton (http://sl4.host.cs.st-andrews.ac.uk/).
Homepage: https://gap-packages.github.io/datastructures
Report issues at https://github.com/gap-packages/datastructures/issues
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
Loading  GRAPE 4.8.5 (GRaph Algorithms using PErmutation groups)
by Leonard H. Soicher (http://www.maths.qmul.ac.uk/~lsoicher/).
Homepage: https://gap-packages.github.io/grape
Report issues at https://github.com/gap-packages/grape/issues
------------------------------------------------------------------------------------------------
Error, LOAD_DYN: failed to load kernel module /home/dima/tmp/gap/pkg/digraphs/bin/x86_64-unknown-openbsd\
7.1-default64-kv8/digraphs.so, Cannot load specified object in
  LOAD_DYN( filename ) at /home/dima/tmp/gap/lib/files.gd:595 called from 
<function "LoadDynamicModule">( <arguments> )
 called from read-eval loop at /home/dima/tmp/gap/pkg/digraphs/init.g:24
Error, was not in any namespace at /home/dima/tmp/gap/lib/variable.g:269 called from
LEAVE_NAMESPACE(  ); at /home/dima/tmp/gap/lib/package.gi:1325 called from
ReadPackage( pkgname, "init.g" ); at /home/dima/tmp/gap/lib/package.gi:1686 called from
<function "LoadPackage">( <arguments> )
 called from read-eval loop at *stdin*:1
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
```
Note that at least some other packages with kernel modules, e.g. `orb` and `io`, work fine.
Also note 
```
$ ldd pkg/digraphs/bin/x86_64-unknown-openbsd7.1-default64-kv8/digraphs.so  
pkg/digraphs/bin/x86_64-unknown-openbsd7.1-default64-kv8/digraphs.so:
Cannot load specified object
pkg/digraphs/bin/x86_64-unknown-openbsd7.1-default64-kv8/digraphs.so: exit status 1
```
as opposed to (working)
```
$ ldd pkg/io/bin/x86_64-unknown-openbsd7.1-default64-kv8/io.so              
pkg/io/bin/x86_64-unknown-openbsd7.1-default64-kv8/io.so:
        Start            End              Type  Open Ref GrpRef Name
        00000a8f5fcb6000 00000a8f5fccf000 dlib  1    0   0      /home/dima/tmp/gap/pkg/io/bin/x86_64-unknown-openbsd7.1-default64-kv8/io.so
```

**Comment by dimpase** [comment]
Found while testing https://github.com/gap-system/gap/pull/5214 as requested by @fingolfin

**Comment by dimpase** [comment]
Apperently `semigroups` kernel module is broken in the same way. Is it due to `macOS` workarounds hackery?

**Comment by james-d-mitchell** [comment]
Thanks for the report @dimpase, I have no idea what to do to resolve this though, and I don't have access to a computer running openbsd to even try to reproduce the issue.  I doubt it is due to macOs workaround hacks, but it might be, any chance you could try deleting lines 96 and 99 of `Makefile.am` and checking if that resolves the issue?

**Comment by james-d-mitchell** [comment]
See also: 

https://github.com/semigroups/Semigroups/issues/328

which seems to be a similar issue.

**Comment by dimpase** [comment]
> try deleting lines 96 and 99 of `Makefile.am` and checking if that resolves the issue?

no, it does not. 

By the way, packages with working on OpenBSD  kernel modules all seem to have [`Makefile.gappkg`](https://github.com/gap-packages/io/blob/master/Makefile.gappkg) included in their makefiles, e.g. https://github.com/gap-packages/io/blob/14f7dddc5881803ec73efb0907e8635281fb00ab/Makefile.in#L13
```
# include shared GAP package build system
GAPPATH = @GAPROOT@
include Makefile.gappkg
```

**Comment by james-d-mitchell** [comment]
Also: can you please confirm whether or not this issue arises with the release version of GAP not the development version? If this does occur with the release version of GAP, can you please also post (at least a link to) the `config.log` file, and give details the compiler, and other package versions?

**Comment by james-d-mitchell** [comment]
> > try deleting lines 96 and 99 of `Makefile.am` and checking if that resolves the issue?
> 
> no, it does not.

Didn't think so. I'm happy to try to resolve this but would first like to know if the issue is actually one in Digraphs and not something that has changed in GAP itself.

**Comment by dimpase** [comment]
> access to a computer running openbsd

I can provide you, and/or @fingolfin with an account on the OpenBSD box I'm testing this on.

**Comment by dimpase** [comment]
> Also: can you please confirm whether or not this issue arises with the release version of GAP not the development version? If this does occur with the release version of GAP, can you please also post (at least a link to) the `config.log` file, and give details of the compiler, and other package versions?

This is with the branch of https://github.com/gap-system/gap/pull/5214
(and Digraphs installed by the GAP's makefile rule fetching all the packages)
 
The same error with GAP 4.12.1 and Digraphs bundled there.

**Comment by fingolfin** [comment]
One suspicion is that libtool perform a lot of black magic to make things work everywhere; and the existing build logic in `Makefile.am` (which was copied from other such files, and was done like that for > 10 years) circumvents that and directly access `.libs/digraphs.so` -- this already may be a source of problems; I actually am kinda surprised it always worked, but perhaps now it doesn't? Anyway, I am just speculating here.

But I also made PR #566 to switch away from using libtool, perhaps it'll help with the OpenBSD issue?

**Comment by james-d-mitchell** [comment]
I believe so, but it'd be good if @dimpase could confirm?

**Comment by dimpase** [comment]
trying the latest version now. While running `make install` I see
```/usr/bin/install -c -d -m 0755 /tmp/lib
/bin/sh ./libtool --silent --mode=install /usr/bin/install -c libgap.la /tmp/lib
ldconfig: /var/run/ld.so.hints.MRgQdFUCt1: Permission denied
```

**Comment by james-d-mitchell** [comment]
Hmm, thanks @dimpase, is this running on a machine with very limited memory by any chance?

**Comment by dimpase** [comment]
no, there is 4GB of RAM, and an active swap of this size too.

It might be threads. I notice that digraphs.so is linked with libpthread. I don't see how to disable this, it appears to have no way to do so.

**Comment by james-d-mitchell** [comment]
Interesting, I don't think that Digraphs is using multi-threading at all, so there should be no reason to link against libpthread, if this is indeed causing the issue. I'll investigate and get back to you.

**Comment by dimpase** [comment]
no, sorry, it seems to be the setup of the C++ environment, which links `pthread` even if not asked:
```
$ cat t.cc   
#include <iostream>
int main() {
                  std::cout << "Hello World!" << std::endl;
                    return 0;
        }
$ c++ t.cc
$ ldd a.out  
a.out:
        Start            End              Type  Open Ref GrpRef Name
        00000b7542353000 00000b7542359000 exe   2    0   0      a.out
        00000b7755a99000 00000b7755b7d000 rlib  0    1   0      /usr/lib/libc++.so.9.0
        00000b77b6f06000 00000b77b6f4c000 rlib  0    2   0      /usr/lib/libc++abi.so.6.0
        00000b7751e78000 00000b7751e84000 rlib  0    1   0      /usr/lib/libpthread.so.27.0
        00000b77814e7000 00000b7781518000 rlib  0    1   0      /usr/lib/libm.so.10.1
        00000b7754baa000 00000b7754ca0000 rlib  0    1   0      /usr/lib/libc.so.97.0
        00000b783916e000 00000b783916e000 ld.so 0    1   0      /usr/libexec/ld.so
$ ./a.out
Hello World!
```

It seems that some code in digraphs is treated as requesting TLS, and this gives
```
libc++abi: std::__libcpp_tls_set failure in __cxa_get_globals()
```

As `gap` is not linked to `pthread`, it could be that some normally done in `main` initialisation of TLS is not happening, and this gives this error.

**Comment by fingolfin** [comment]
@dimpase can you tell us:
- the output of `make clean && make V=1` inside the Digraphs package?
- the content of GAP's `sysinfo.gap`, i.e.: the output of `cat $(make print-GAPPATH | cut -d= -f2-)/sysinfo.gap`

**Comment by dimpase** [comment]
Please see https://users.ox.ac.uk/~coml0531/tmp/d.log for `make V=1` output, and
https://users.ox.ac.uk/~coml0531/tmp/sysinfo.gap

**Comment by dimpase** [comment]
By the way, I noticed a bug in Makefile.in, which I fixed and got a more meaningful
```
$ ldd bin/x86_64-unknown-openbsd7.3-default64-kv9/digraphs.so                                                                                        
bin/x86_64-unknown-openbsd7.3-default64-kv9/digraphs.so:
        Start            End              Type  Open Ref GrpRef Name
        0000040d17fc1000 0000040d18054000 dlib  1    0   0      /home/dima/tmp/gap/pkg/digraphs/bin/x86_64-unknown-openbsd7.3-default64-kv9/digraphs.so
        0000040cfaa82000 0000040cfab66000 rlib  0    1   0      /usr/lib/libc++.so.9.0
        0000040cda93e000 0000040cda984000 rlib  0    1   0      /usr/lib/libc++abi.so.6.0
```
(see, no pthread any more!) - that's after I did
```
KEXT_LDFLAGS += -lc++  # for bliss: add C++ library
# KEXT_LDFLAGS += -lstdc++  # for bliss: add C++ library
```
- by right, Clang's `libc++` is not compatible with GNU's `libstdc++`. 

But I still get a crash in the tests:
```
gap> TestPackage("digraphs");
...
# line 367 of 432 (84%)libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
```

**Comment by dimpase** [comment]
@james-d-mitchell : yes, sure please send me your public ssh key and preferred login name

**Comment by dimpase** [comment]
Is `homos.c` meant to be compiled with a plain C compiler, not C++ ? It's strange that the error is a C++ error...

**Comment by fingolfin** [comment]
Try gmake instead of make

**Comment by james-d-mitchell** [comment]
aha thanks! @fingolfin

**Comment by dimpase** [comment]
that's why I suggested you look at ~dima/bin, where I made a link
make->gmake and tar->gtar

**Comment by james-d-mitchell** [comment]
Aha, sorry missed that, thanks both. 

I've investigated this just now, and I can't really understand what's happening. With both digraphs and gap compiled in debug mode with `CFLAGS` and `CXXFLAGS` set to `-O0 -g3`, the following (from one of the digraphs tests):

~~~
gap> HomomorphismDigraphsFinder(CompleteDigraph(2),
>                               CompleteDigraph(3),
>                               fail,    # hook
>                               [],      # user_param
>                               1,       # limit
>                               2,       # hint      (rank 2)
>                               1,       # injective (yes)
>                               [1, 2],  # only values 1 and 2 in the image
>                               [1],     # 1 -> 1
>                               fail,    # no colours
>                               fail);   # no colours
~~~

causes a seg fault `SIGSEGV` in the debugger this shows as:

~~~
Process 7167 stopped
* thread #1, stop reason = signal SIGSEGV
    frame #0: 0x000009e11b15208a
->  0x9e11b15208a: movq   %rdx, (%rax,%rcx,8)
    0x9e11b15208e: movw   -0x1a(%rbp), %ax
    0x9e11b152092: addw   $0x1, %ax
    0x9e11b152096: movw   %ax, -0x1a(%rbp)
(lldb) up
error: Already at the top of the stack.
~~~

So, we're not in a function provided by digraphs here, and the depth of the call stack is 1. Other functions in the digraphs kernel extension can be called and work just fine with no seg fault. I'm not sure how to debug this further...

**Comment by dimpase** [comment]
Is this with `KEXT_LDFLAGS += -lc++  # for bliss: add C++ library` as suggested above?

**Comment by james-d-mitchell** [comment]
Yes, it is @dimpase.

**Comment by dimpase** [comment]
By the way, `src/homos.c` has calls to `malloc`, but no calls to `free`.

Looks like a certain memory leak to me (assuming `malloc()` is the system `malloc`, not something provided by GAP).
Actually, `malloc()` in a GAP kernel extension looks like it's asking for trouble.

**Comment by james-d-mitchell** [comment]
> By the way, src/homos.c has calls to malloc, but no calls to free.

This is entirely intentional. The memory is allocated once at the first call to the homomorphism finding code, and then released when the programme exits. So, no memory leak. 

> Actually, malloc() in a GAP kernel extension looks like it's asking for trouble.

I don't agree, this happens all over the place, and is not likely to be the source of this issue (Digraphs has been this way for nearly 10 years, and this is the first such issue we are having). 

I'm not saying that the issue here isn't related to what we are doing in `homos.c` just that I don't think there's the type of issue that you indicated in your last comment.

**Comment by dimpase** [comment]
OK, never mind then, sorry for noise.

**Comment by james-d-mitchell** [comment]
Trying again in gbd rather than lldb I can get a stack trace, and I might be able to debug further from that. I'll post a message here if I make any progress.

**Comment by dimpase** [comment]
by the way, I've installed bliss in /usr/local, too - but using it instead gives the same error.

I've also tried to narrow down where the crash comes from, and it seems to be happening in the loop starting at
https://github.com/digraphs/Digraphs/blob/c96540aa7d446b8863341688c26e1d470a47c8de/src/homos.c#L1619
after something like 154 bliss graphs had been created.

**Comment by james-d-mitchell** [comment]
I'm pretty sure that the machine is just running out of memory, I'll investigate some more.

**Comment by dimpase** [comment]
During the crash, I see the memory consumption of the GAP process to go to 1.4Gb. The machine has 4Gb of RAM.

**Comment by dimpase** [comment]
For some reason, GAP cannot be started there if I pass `-m` option bigger than 1G. Why does it happen?

**Comment by james-d-mitchell** [comment]
> For some reason, GAP cannot be started there if I pass `-m` option bigger than 1G. Why does it happen?

No idea, this must be an issue with the machine rather than GAP itself I think, I am routinely using gap with >> 1G on my laptop.

**Comment by james-d-mitchell** [comment]
I can "fix" this by doing a couple of things:

1. Make the allocation of memory for the homomorphism finding code more conservative (this is something that we've been meaning to do for some time, there's another issue about exactly this issue, can't currently locate it). 

2. Check that the `malloc` calls succeed, and do something (like give an error or something) if it does. 

Does that sound reasonable?

**Comment by dimpase** [comment]
OK, I've increased `ulimit` on memory for every user, and now I can pass `-m 2G` to GAP.
And the tests are passing now.

Sorry for noise. So I think the net outcome here is that 

1. `ulimit` on memory should be `>2G`. 
2.  `Makefile.in` has to be fixed to make sure the correct C++ library (libstdc++ vs libc++) is passed (or none for external bliss), see above.

**Comment by dimpase** [comment]
> Is this with `KEXT_LDFLAGS += -lc++ # for bliss: add C++ library` as suggested above?

By the way, very similar issue (wrong `KEXT_LDFLAGS`) in https://github.com/semigroups/Semigroups/issues/928

**Comment by james-d-mitchell** [comment]
Just to double check @dimpase this issue is now resolved right?

**Comment by dimpase** [comment]
oops, I missed this. I'll check and report.

**Comment by dimpase** [comment]
with the current packages and GAP master, the default building is stuck at
```
gmake[1]: Entering directory '/home/dima/software/gap/pkg/semigroups/libsemigroups'
  CXX      src/libsemigroups_la-bipart.lo
  CXX      src/libsemigroups_la-bmat8.lo
  CXX      src/libsemigroups_la-cong-intf.lo
  CXX      src/libsemigroups_la-cong-pair.lo
  CXX      src/libsemigroups_la-cong.lo
  CXX      src/libsemigroups_la-constants.lo
  CXX      src/libsemigroups_la-coset.lo
  CXX      src/libsemigroups_la-exception.lo
In file included from src/exception.cpp:33:
/home/dima/software/gap/pkg/semigroups/libsemigroups/extern/backward-cpp/backward.hpp:1337:25: error: no member named 'begin' in 'backward::StackTrace'
      load_addresses(st.begin(), static_cast<int>(st.size()));
                     ~~ ^
src/exception.cpp:50:8: note: in instantiation of function template specialization 'backward::TraceResolverImplBase::load_stacktrace<backward::StackTrace>' requested here
    tr.load_stacktrace(st);
       ^
1 error generated.
```

**Comment by dimpase** [comment]
oops, wrong package
