### ISSUE TITLE
New release with PR #571 in?

### ISSUE THREAD

**Issue by fingolfin** [digraphs/Digraphs#573]
Would it be possible to get a 1.6.2 release by mid April? Then that could be included in GAP 4.13, and it'd get us one step closer to resolving https://github.com/gap-system/gap/issues/5361 :-)

**Comment by james-d-mitchell** [comment]
Sure, I'll try to make a release today or tomorrow!

**Comment by james-d-mitchell** [comment]
Hopefully resolved in v1.6.2! @fingolfin
