### ISSUE TITLE
Confusing error message in DigraphByEdges

### ISSUE THREAD

**Issue by ChrisJefferson** [digraphs/Digraphs#645]
```
gap> DigraphByEdges([ [1,2], [3,0] ]);
Error, the 1st argument <edges> must not contain values greater than 3, the 2nd argument <n>,
```

Well, nothing is greater than 3! What the error means (after I stuck some messages in the code, in reality the graph I was working on was much, much bigger :) ) is edges must contain only positive integers which are not greater than 3.

**Comment by james-d-mitchell** [comment]
I'm going to mark this as resolved, unless you disagree @ChrisJefferson

**Comment by ChrisJefferson** [comment]
No, looks good!
