### ISSUE TITLE
Compute subgraphs

### ISSUE THREAD

**Issue by MeikeWeiss** [digraphs/Digraphs#670]
It would be nice to have a method that computes, for a given digraph G and a digraph H, all subgraphs of G that are isomorphic to H. These subgraphs do not have to be induced subgraphs. It can be computed theoretically by MonomorphismsDigraphs but the output is here is a transformation and not a digraph. Moreover, the length of the output of this method for G isomorphic to H is the order of the automorphism group but G has only one subgraph. So using this method is maybe not the best way.

I have some code that computes all subgraphs with the output of MonomorphismsDigraphs, but it only works for certain subgraphs so far.  I will see if it can be generalised. But maybe an algorithm not based on MonomorphismsDigraphs would be better.

**Comment by james-d-mitchell** [comment]
Thanks for the suggestion @MeikeWeiss I'm happy to think about this, this week during GAP days. Is it possible for you to post some examples?

**Comment by MeikeWeiss** [comment]
Consider for example G=K_4 and H=K_{2,2}, i.e. the complete bipartite graph with both partition sets of size two. Assume the vertices of G are numbered from 1 to 4 and we define graphs isomorphic to K_{2,2} by giving the vertices of the partition sets. The subgraphs of G isomorphic to H are the following and these have to be the output of the method:
{ {1, 2}, {3, 4} }, { {1, 3}, {2,4} }, { {1, 4}, {2, 3} }

As another example consider as G the following digraph:
~~~
g:=DigraphByEdges([ [ 1, 3 ], [ 3, 1 ], [ 1, 4 ], [ 4, 1 ], [ 3, 4 ], [ 4, 3 ], [ 1, 5 ], [ 5, 1 ], [ 3, 5 ], [ 5, 3 ], [ 4, 5 ], [ 5, 4 ], [ 2, 3 ],
  [ 3, 2 ], [ 2, 4 ], [ 4, 2 ], [ 2, 5 ], [ 5, 2 ] ]);
~~~
and H=K_4. Then the following vertex sets of G form a graph isomorphic to H and these have to be the output of the method:
{1,3,4,5}, {2,3,4,5}

**Comment by james-d-mitchell** [comment]
Thanks @MeikeWeiss do you have any bigger examples where you start to see some poor performance?

**Comment by MeikeWeiss** [comment]
@james-d-mitchell For example, the following call is cancelled after 10minutes with an error due to a memory limit:

~~~
MonomorphismsDigraphs(CompleteDigraph(4),CompleteDigraph(12));;
~~~

But this is the extrem case and I noticed also that the method is quite fast for the graphs we are interested in. I think I had remembered that wrong.

**Comment by james-d-mitchell** [comment]
Here's a couple of attempts at an implementation, if you could check if these are valid that'd be great @MeikeWeiss,

~~~
ApplyHomomorphismNC := function(D1, D2, t)
  local old, new, v, im;
  old := OutNeighbours(D1);
  new := List([1 .. DigraphNrVertices(D2)], x -> []);
  for v in DigraphVertices(D1) do
    im := v ^ t;
    if not IsBound(new[im]) then
      new[im] := [];
    fi;
    Append(new[im], OnTuples(old[v], t));
  od;
  return Digraph(new);
end;

SubgraphsV1 := function(H, G)
  local maps, result, map, rep;

  maps := MonomorphismsDigraphsRepresentatives(H, G);

  result := [];

  for map in maps do
    rep := ApplyHomomorphismNC(H, G, map);
    UniteSet(result, Orbit(AutomorphismGroup(G), rep, OnDigraphs));
  od;
  return result;
end;

SubgraphsV2 := function(H, G)
  local GV, HN, o, reps, result, map, rep;

  GV := DigraphVertices(G);
  HN := DigraphNrVertices(H);
  o := Orbits(AutomorphismGroup(G), Combinations(GV, HN), OnSets);
  reps := List(o, Representative);
  result := [];

  for rep in reps do
    map :=
    HomomorphismDigraphsFinder(H,                   # domain
                               G,                   # range
                               fail,                # hook
                               [],                  # user_param
                               1,                   # max_results
                               HN,                  # hint (i.e. rank)
                               true,                # injective
                               rep,                 # image
                               [],                  # partial_map
                               fail,                # colors1
                               fail,                # colors2
                               DigraphWelshPowellOrder(H));
    if Length(map) <> 0 then
      map := map[1];
      rep := ApplyHomomorphismNC(H, G, map);
      Append(result, Orbit(AutomorphismGroup(G), rep, OnDigraphs));
    fi;
  od;
  return result;
end;
~~~

**Comment by MeikeWeiss** [comment]
Thanks! I tested some examples I have and the output seems to be correct. For the following example the version 1 is significant slower than the second version:
~~~
g:=DigraphByEdges([ [ 1, 3 ], [ 3, 1 ], [ 1, 4 ], [ 4, 1 ], [ 1, 5 ], [ 5, 1 ], [ 1, 6 ], [ 6, 1 ], [ 1, 7 ], [ 7, 1 ], [ 1, 8 ], [ 8, 1 ], [ 1, 9 ],
  [ 9, 1 ], [ 1, 10 ], [ 10, 1 ], [ 1, 11 ], [ 11, 1 ], [ 1, 12 ], [ 12, 1 ], [ 2, 3 ], [ 3, 2 ], [ 2, 4 ], [ 4, 2 ], [ 2, 5 ], [ 5, 2 ], [ 2, 6 ],
  [ 6, 2 ], [ 2, 7 ], [ 7, 2 ], [ 2, 8 ], [ 8, 2 ], [ 2, 9 ], [ 9, 2 ], [ 2, 10 ], [ 10, 2 ], [ 2, 11 ], [ 11, 2 ], [ 2, 12 ], [ 12, 2 ],
  [ 3, 4 ], [ 4, 3 ], [ 3, 12 ], [ 12, 3 ], [ 4, 5 ], [ 5, 4 ], [ 5, 6 ], [ 6, 5 ], [ 6, 7 ], [ 7, 6 ], [ 7, 8 ], [ 8, 7 ], [ 8, 9 ], [ 9, 8 ],
  [ 9, 10 ], [ 10, 9 ], [ 10, 11 ], [ 11, 10 ], [ 11, 12 ], [ 12, 11 ] ]);
SubgraphsV1(CompleteMultipartiteDigraph([2,5]),g);
~~~

For the following example 
~~~
g:=DigraphByEdges([ [ 1, 3 ], [ 3, 1 ], [ 1, 4 ], [ 4, 1 ], [ 1, 5 ], [ 5, 1 ], [ 1, 6 ], [ 6, 1 ], [ 1, 7 ], [ 7, 1 ], [ 1, 8 ], [ 8, 1 ], [ 1, 9 ],
  [ 9, 1 ], [ 1, 10 ], [ 10, 1 ], [ 1, 11 ], [ 11, 1 ], [ 1, 12 ], [ 12, 1 ], [ 1, 13 ], [ 13, 1 ], [ 1, 14 ], [ 14, 1 ], [ 1, 15 ], [ 15, 1 ],
  [ 1, 16 ], [ 16, 1 ], [ 2, 3 ], [ 3, 2 ], [ 2, 4 ], [ 4, 2 ], [ 2, 5 ], [ 5, 2 ], [ 2, 6 ], [ 6, 2 ], [ 2, 7 ], [ 7, 2 ], [ 2, 8 ],
  [ 8, 2 ], [ 2, 9 ], [ 9, 2 ], [ 2, 10 ], [ 10, 2 ], [ 2, 11 ], [ 11, 2 ], [ 2, 12 ], [ 12, 2 ], [ 2, 13 ], [ 13, 2 ], [ 2, 14 ], [ 14, 2 ], [ 2, 15 ],
  [ 15, 2 ], [ 2, 16 ], [ 16, 2 ], [ 3, 4 ], [ 4, 3 ], [ 3, 16 ], [ 16, 3 ], [ 4, 5 ], [ 5, 4 ], [ 5, 6 ], [ 6, 5 ], [ 6, 7 ], [ 7, 6 ],
  [ 7, 8 ], [ 8, 7 ], [ 8, 9 ], [ 9, 8 ], [ 9, 10 ], [ 10, 9 ], [ 10, 11 ], [ 11, 10 ], [ 11, 12 ], [ 12, 11 ], [ 12, 13 ], [ 13, 12 ], [ 13, 14 ],
  [ 14, 13 ], [ 14, 15 ], [ 15, 14 ], [ 15, 16 ], [ 16, 15 ] ]);
SubgraphsV2(CompleteMultipartiteDigraph([2,7]),g);;
~~~
version 2 returns the information:  
#I  You are calculating `Orbits' with a large set of seeds.
#I  If you gave a domain and not seeds consider `OrbitsDomain' instead.
And version 1 needs here longer than a couple of minutes.

But in our application these are the example with maximal (exponential) number of subgraphs.

**Comment by MeikeWeiss** [comment]
[Examples.zip](https://github.com/user-attachments/files/16802407/Examples.zip)

Here are some examples of graphs that all should have (n-2)/2 subraphs isomorphic to K_4 if n is the number of vertices.

**Comment by james-d-mitchell** [comment]
Just for the record, the correct value in the previous comment is (2n - 6)/2.
